input {
  beats {
    port => 5044
    add_field => { "[@metadata][source]" => "beats" }
  }

  tcp {
    port => 5000
    codec => json_lines
    add_field => { "[@metadata][source]" => "tcp_json" }
  }
}

filter {
  if [@metadata][source] == "tcp_json" and [timestamp] {
    date {
      match => ["timestamp", "ISO8601"]
      target => "@timestamp"
    }
  }
}

output {
  if [@metadata][source] == "tcp_json" {
    elasticsearch {
      hosts => ["http://es-hot:9200"]
      index => "logstash-%{+YYYY.MM.dd}"
    }
  } else if [@metadata][source] == "beats" {
    elasticsearch {
      hosts => ["http://es-hot:9200"]
      index => "docker-logs-%{+YYYY.MM.dd}"
    }
  }

  stdout {
    codec => rubydebug
  }
}
